name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Detect repository type and set base path
        id: basepath
        run: |
          REPO_NAME="${{ github.repository }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_ONLY_NAME="${REPO_NAME#*/}"
          
          echo "Repository: $REPO_NAME"
          echo "Owner: $REPO_OWNER"
          echo "Repo name: $REPO_ONLY_NAME"
          
          # 检查是否为用户名.github.io仓库
          if [[ "$REPO_ONLY_NAME" == "$REPO_OWNER.github.io" ]]; then
            echo "Detected user/organization GitHub Pages site"
            echo "BASE_PATH=" >> $GITHUB_OUTPUT
            echo "NEXT_PUBLIC_BASE_PATH=" >> $GITHUB_ENV
          else
            echo "Detected project GitHub Pages site"
            echo "BASE_PATH=/$REPO_ONLY_NAME" >> $GITHUB_OUTPUT
            echo "NEXT_PUBLIC_BASE_PATH=/$REPO_ONLY_NAME" >> $GITHUB_ENV
          fi
          
          echo "Final BASE_PATH: $(cat $GITHUB_OUTPUT | grep BASE_PATH | cut -d'=' -f2)"
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: action/secretballot-frontend/package-lock.json
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          
      - name: Install dependencies
        run: |
          cd action/secretballot-frontend
          npm ci
          
      - name: Build with Next.js
        run: |
          cd action/secretballot-frontend
          echo "Building with BASE_PATH: $NEXT_PUBLIC_BASE_PATH"
          npm run build
          
      - name: Create .nojekyll file
        run: |
          cd action/secretballot-frontend/out
          touch .nojekyll
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: action/secretballot-frontend/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
